---

frequency: 426000000
frequencies: 
        - 424000000
        - 425000000
        - 426000000
        - 427000000
bw: 1
cr: 0
sf: 9
preamble_length: 16
preamble_slots: 1
beacon_msg: 'KG5VBY Beacon Test'
fec_algo: 'RSV'
conv_rate: 2
conv_order: 7
rs_num_roots: 8
cw_test_mode: 0
preamble_test_mode: 0
test_fec: 0
num_offsets: 4
has_gps: 0
pocsag_freq: 439987500
pocsag_beacon_interval: 30

...
