---

frequency: 426000000
frequencies: 
        - 424000000
        - 425000000
        - 426000000
        - 427000000
bw: 1
cr: 0
sf: 9
preamble_length: 16
preamble_slots: 1
payload_length: 32
beacon_msg: 'KG5VBY Beacon Test'
# NONE = 0; INTERLEAVE = 1; CONV = 2; RSV = 3; RSVGOLAY = 4;
fec_algo: 4
conv_rate: 2
conv_order: 7
rs_num_roots: 8
cw_test_mode: 0
preamble_test_mode: 0
test_fec: 0
num_offsets: 4
gps_en: 0
pocsag_enabled: 0
pocsag_freq: 439987500
pocsag_beacon_interval: 120
log_packets_en: 1
log_boot: 1
watchdog_timer_en: 1

...
